FROM python:3.11-slim

WORKDIR /app

# نصب ODBC Driver برای SQL Server
RUN apt-get update && apt-get install -y \
    gnupg \
    curl \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && rm -rf /var/lib/apt/lists/*

# کپی requirements.txt
COPY requirements.txt . 

# نصب Python packages
RUN pip install --no-cache-dir -r requirements.txt

# کپی کل پروژه
COPY . . 

# اجرای FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
